### ISSUE TITLE
Missing dependency (on packaging)

### ISSUE THREAD

**Issue by tdoublep** [IBM/lale#1078]
It looks like `packaging` needs to be added to Lale's dependency list. 

See following example:
```
$ conda create -n lale-test python=3.7
$ conda activate lale-test
$ pip install lale
$ python -c "from lale.lib.sklearn import OneHotEncoder"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tpa/anaconda3/envs/lale-test/lib/python3.7/site-packages/lale/lib/sklearn/__init__.py", line 198, in <module>
    from .one_hot_encoder import OneHotEncoder
  File "/Users/tpa/anaconda3/envs/lale-test/lib/python3.7/site-packages/lale/lib/sklearn/one_hot_encoder.py", line 19, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by shyamsantoki** [comment]
This issue is [sklearn](https://github.com/scikit-learn/scikit-learn) related. Furthermore, I did not get any errors when I created a conda environment using Python 3.10.

```py
$ conda create -n lale-test python=3.10
$ conda activate lale-test
$ pip install lale
$ python -c "from lale.lib.sklearn import OneHotEncoder"
```
