### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ghost** [IBM/lale#384]
Hi All,
Simple installation step does not work for me on Catalina OSX inside a virtual environment, Python 3.7.7 installed via Homebrew:
```
(pylale) albert@...> pip3 install lale[full]
zsh: no matches found: lale[full]
```
Similarly:
```
(pylale) albert@...> pip3 install lale[full] --isolated
zsh: no matches found: lale[full]
```
Same with cloned git repository:
```
(pylale) albert@... lale> pip3 install .[full,test]
zsh: no matches found: .[full,test]
(pylale) albert@... lale> pip3 install .[full,test] --isolated
zsh: no matches found: .[full,test]
```
It works without [full,test] but no tests ...

**Comment by kiran-kate** [comment]
Thank you for reporting the issue. Could you try `pip3 install 'lale[full]'` as per the solution suggested here: https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity?

**Comment by Albert65** [comment]
Thank you very much. It works for now.
You might be interested in test results. Almost all of them have passed. Few errors:
```
======================================================================
ERROR: lale.lib.aif360 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lale.lib.aif360
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/albert/tmp/lale/lale/lib/aif360/__init__.py", line 46, in <module>
    from .disparate_impact_remover import DisparateImpactRemover
  File "/Users/albert/tmp/lale/lale/lib/aif360/disparate_impact_remover.py", line 15, in <module>
    import aif360.algorithms.preprocessing
  File "/Users/albert/pylale/lib/python3.7/site-packages/aif360/algorithms/preprocessing/__init__.py", line 2, in <module>
    from aif360.algorithms.preprocessing.lfr import LFR
  File "/Users/albert/pylale/lib/python3.7/site-packages/aif360/algorithms/preprocessing/lfr.py", line 5, in <module>
    from aif360.algorithms.preprocessing.lfr_helpers import helpers as lfr_helpers
  File "/Users/albert/pylale/lib/python3.7/site-packages/aif360/algorithms/preprocessing/lfr_helpers/helpers.py", line 2, in <module>
    from numba.decorators import jit
ModuleNotFoundError: No module named 'numba.decorators'


======================================================================
ERROR: lale.lib.spacy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lale.lib.spacy
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/albert/tmp/lale/lale/lib/spacy/__init__.py", line 1, in <module>
    from .glove_embedding_encoder import GloveEmbeddingEncoder
  File "/Users/albert/tmp/lale/lale/lib/spacy/glove_embedding_encoder.py", line 178, in <module>
    lale.docstrings.set_docstrings(GloveEmbeddingEncoderImpl, _combined_schemas)
  File "/Users/albert/tmp/lale/lale/docstrings.py", line 178, in set_docstrings
    assert impl_cls.__doc__ is None
AssertionError


======================================================================
ERROR: lale.lib.tensorflow (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lale.lib.tensorflow
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/albert/tmp/lale/lale/lib/tensorflow/__init__.py", line 1, in <module>
    from .use_pretrained_encoder import USEPretrainedEncoder
  File "/Users/albert/tmp/lale/lale/lib/tensorflow/use_pretrained_encoder.py", line 234, in <module>
    lale.docstrings.set_docstrings(USEPretrainedEncoderImpl, _combined_schemas)
  File "/Users/albert/tmp/lale/lale/docstrings.py", line 178, in set_docstrings
    assert impl_cls.__doc__ is None
AssertionError


======================================================================
FAIL: test_USEPretrainedEncoder (test.test_nlp_operators.TestTextEncoders)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/albert/tmp/lale/test/test_nlp_operators.py", line 22, in test_encoder
    module = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/albert/tmp/lale/lale/lib/tensorflow/__init__.py", line 1, in <module>
    from .use_pretrained_encoder import USEPretrainedEncoder
  File "/Users/albert/tmp/lale/lale/lib/tensorflow/use_pretrained_encoder.py", line 234, in <module>
    lale.docstrings.set_docstrings(USEPretrainedEncoderImpl, _combined_schemas)
  File "/Users/albert/tmp/lale/lale/docstrings.py", line 178, in set_docstrings
    assert impl_cls.__doc__ is None
AssertionError

----------------------------------------------------------------------
Ran 371 tests in 4208.572s

FAILED (failures=1, errors=3, skipped=1)
make: *** [run_tests] Error 1
```
